2025-09-28 12:01:40.792 ERROR (MainThread) [homeassistant.config] Invalid config for 'scene' at scenes.yaml, line 2: State for climate.hvac should be a string for dictionary value 'states->0->entities', got None, please check the docs at https://www.home-assistant.io/integrations/scene
2025-09-28 12:01:40.792 ERROR (MainThread) [homeassistant.config] Invalid config for 'scene' at scenes.yaml, line 12: State for climate.hvac should be a string for dictionary value 'states->0->entities', got None, please check the docs at https://www.home-assistant.io/integrations/scene
2025-09-28 12:01:40.875 ERROR (MainThread) [homeassistant.components.switch] The demo platform for the switch integration does not support platform setup. Please remove it from your config.
2025-09-28 12:01:40.876 ERROR (MainThread) [homeassistant.components.climate] The demo platform for the climate integration does not support platform setup. Please remove it from your config.
2025-09-28 12:01:40.876 ERROR (MainThread) [homeassistant.components.light] The demo platform for the light integration does not support platform setup. Please remove it from your config.
2025-09-28 12:01:40.876 ERROR (MainThread) [homeassistant.components.cover] The demo platform for the cover integration does not support platform setup. Please remove it from your config.
2025-09-28 12:01:40.876 ERROR (MainThread) [homeassistant.components.fan] The demo platform for the fan integration does not support platform setup. Please remove it from your config.
2025-09-28 12:34:21.181 ERROR (MainThread) [aiohttp.server] Error handling request from 162.55.180.156
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 437, in post
    response = await shield(
               ^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2835, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2878, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 834, in entity_service_call
    raise ServiceNotSupported(call.domain, call.service, entity.entity_id)
homeassistant.exceptions.ServiceNotSupported: Entity cover.pergola_roof does not support action cover.toggle
2025-09-28 12:34:25.332 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities scene.demo_daytime are missing or not currently available
